---
- name: Modulo de Instalación de Erratas Full
  hosts: all
  gather_facts: False
  become: true
  tasks:
  - name: Instalacion de Erratas Full 
    ansible.builtin.yum:
      name: '*' 
      state: latest
      update_cache: yes
